[bastion]
51.250.12.248 ansible_user=soldatov

[webservers]
10.0.1.23 ansible_user=soldatov
10.0.2.7 ansible_user=soldatov

[webservers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q soldatov@51.250.12.248"'
