---
- name: Set MOTD using external variable file
  hosts: localhost
  connection: local
  become: true

  vars_files:
    - motd_vars.yaml

  tasks:
    - name: Write MOTD from variable
      copy:
        content: "{{ my_motd_message }}"
        dest: /etc/motd
        owner: root
        group: root
        mode: "0644"