---
- name: Install and enable tuned
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Update package list and install tuned
      apt:
        name: tuned
        state: present
        update_cache: yes

    - name: Start the tuned service
      systemd:
        name: tuned
        state: started

    - name: Enable tuned to start on boot
      systemd:
        name: tuned
        enabled: yes
        
